export default {
  COLORS: {
    DEFAULT: '#DCDCDC',
    PRIMARY: '#1EA8FF',
    LABEL: '#1EFFC9',
    INFO: '#1EA8FF',
    ERROR: '#F44336',
    SUCCESS: '#4CAF50',
    WARNING: '#FF9800',
    MUTED: '#979797',
    INPUT: '#DCDCDC',
    ACTIVE: '#1EA8FF',
    BUTTON_COLOR: '#1EA8FF',
    PLACEHOLDER: '#9FA5AA',
    SWITCH_ON: '#1EA8FF',
    SWITCH_OFF: '#D4D9DD',
    GRADIENT_START: '#1EA8FF',
    GRADIENT_END: '#1EFFC9',
    PRICE_COLOR: '#EAD5FB',
    BORDER_COLOR: '#E7E7E7',
    BLOCK: '#E7E7E7',
    CAPTION: '#4A4A4A',
  },
  SIZES: {
    BLOCK_SHADOW_RADIUS: 2,
  }
};
